# Autograd with tensors

In [0]:
import torch

In [0]:
w = torch.randn(4,3,requires_grad=True)

In [3]:
w

tensor([[-0.7589, -0.3603,  0.7678],
        [-1.5837,  0.3327, -0.1244],
        [-1.9141, -0.2149, -0.7534],
        [-0.0313,  0.0106,  0.7625]], requires_grad=True)

In [4]:
w.requires_grad_(False)
w

tensor([[-0.7589, -0.3603,  0.7678],
        [-1.5837,  0.3327, -0.1244],
        [-1.9141, -0.2149, -0.7534],
        [-0.0313,  0.0106,  0.7625]])

In [5]:
w.requires_grad_(True)

tensor([[-0.7589, -0.3603,  0.7678],
        [-1.5837,  0.3327, -0.1244],
        [-1.9141, -0.2149, -0.7534],
        [-0.0313,  0.0106,  0.7625]], requires_grad=True)

In [6]:
y = torch.exp(w)
print(y)

tensor([[0.4682, 0.6975, 2.1551],
        [0.2052, 1.3948, 0.8831],
        [0.1475, 0.8066, 0.4707],
        [0.9692, 1.0106, 2.1436]], grad_fn=<ExpBackward>)


In [7]:
print(y.grad_fn)

In [8]:
outp = y.mean()
print(outp)

tensor(0.9460, grad_fn=<MeanBackward0>)


In [9]:
print(w.grad)

None


In [0]:
outp.backward()

In [11]:
print(w.grad)

tensor([[0.0390, 0.0581, 0.1796],
        [0.0171, 0.1162, 0.0736],
        [0.0123, 0.0672, 0.0392],
        [0.0808, 0.0842, 0.1786]])


In [12]:
print(w.detach())

tensor([[-0.7589, -0.3603,  0.7678],
        [-1.5837,  0.3327, -0.1244],
        [-1.9141, -0.2149, -0.7534],
        [-0.0313,  0.0106,  0.7625]])


In [15]:
print(outp.requires_grad)

with torch.no_grad():
  outp = (w+y).mean()
  
print(outp.requires_grad)  

True
False
